//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Ad alaný boþ geçilemez.")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Marka alaný boþ geçilemez.")]
        public string Marka { get; set; }
        public Nullable<int> KategoriId { get; set; }
        [Required(ErrorMessage = "Fiyat alaný boþ geçilemez.")]
        public Nullable<decimal> Fiyat { get; set; }
        [Required(ErrorMessage = "Stok alaný boþ geçilemez.")]
        public Nullable<int> Stok { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
